version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <your_account_id>.dkr.ecr.<region>.amazonaws.com)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 107368385520.dkr.ecr.us-east-1.amazonaws.com/my-repo:${IMAGE_TAG} .
      - docker tag 107368385520.dkr.ecr.us-east-1.amazonaws.com/my-repo:${IMAGE_TAG} 107368385520.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 107368385520.dkr.ecr.us-east-1.amazonaws.com/my-repo:${IMAGE_TAG}
      - docker push 107368385520.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
      - printf '[{"name":"test","imageUri":"%s"}]' 107368385520.dkr.ecr.us-east-1.amazonaws.com/my-repo:${IMAGE_TAG} > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
